### ISSUE TITLE
thank you for envvar

### ISSUE THREAD

**Issue by torkus** [gcv/envvar#1]
Hi,

I wanted to thank you for creating envvar. I've just finished [incorporating it](https://github.com/ogri-la/wowman/commit/28aee67b7ada09ca7dfcf987a32d93a529016c44) into my program and it was a breeze. It saved me some time and hassle and I'm grateful for that.

I read the [discussion versus environ](https://grokbase.com/t/gg/clojure/148d4hrzt6/ann-envvar-1-1-0-a-library-for-handling-environment-variables) and inspected the code of both projects and chose yours because it was smaller and simpler to understand and the `with-env` binding and `@env` dereferencing were just what I needed right there in the README. environ lacked this.

:1st_place_medal:

**Comment by gcv** [comment]
Thank you for the kind words, @torkus! Glad you found it useful.
